# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Check if disks already exist
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk_info:
    name: "disk_{{ item.drive_letter }}_{{ item.partition_label }}"
    resource_group: "{{ resource_group }}"
  register: r_azure_rm_manageddisk_info
  loop: "{{ os_storage }}"

- debug: var=r_azure_rm_manageddisk_info
  delegate_to: localhost
  when: debug | bool

- name: Create and attach the managed disk to VM
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk:
    name: "disk_{{ item.drive_letter }}_{{ item.partition_label }}"
    resource_group: "{{ resource_group }}"
    disk_size_gb: "{{ storage_devices.max_size_gb|int }}"
    managed_by: "{{ machine_name }}"
    os_type: "{{ os_type }}"
    storage_account_type: "{{ storage_devices.specifications.storage_account_type }}"
    tags: "{{ {
                'Name': 'disk_'+item.drive_letter+'_'+item.partition_label,
                'Partition_label': item.partition_label,
                'Drive_letter': item.drive_letter
              }
              | combine(custom_tags) }}"
  register: r_azure_rm_manageddisk
  when: r_azure_rm_manageddisk_info|json_query('results[*].ansible_info.azure_managed_disk[*].name[]|[?contains(@, `disk_'+item.drive_letter+'_'+item.partition_label+'`) == `true`]')|length==0
  loop: "{{ os_storage }}"

- debug: var=r_azure_rm_manageddisk
  delegate_to: localhost
  when: debug | bool
