# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- include_tasks: derive_volumes_need.yml

- name: Create volume
  delegate_to: localhost
  oracle.oci.oci_blockstorage_volume:
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ availability_domain }}"
    display_name: "{{ machine_name }}_disk{{ item }}"
    size_in_gbs: "{{ storage_devices.max_size_gb|int }}"
    freeform_tags : "{{ {'Name': 'disk'+item} | combine(custom_tags) }}"
  register: r_oci_blockstorage_volume_present
  loop: "{{ query('sequence', 'start=1 end='+(number_of_devices)|string) }}"

- debug: var=r_oci_blockstorage_volume_present
  delegate_to: localhost
  when: debug | bool

- name: Get instances ID
  delegate_to: localhost
  oracle.oci.oci_compute_instance_facts:
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ availability_domain }}"
    display_name: "{{ machine_name }}"
    lifecycle_state: RUNNING
  register: r_oci_compute_instance_facts
  failed_when: r_oci_compute_instance_facts.instances|length == 0

- debug: var=r_oci_compute_instance_facts
  delegate_to: localhost
  when: debug | bool

- name: Create volume attachment
  delegate_to: localhost
  oracle.oci.oci_compute_volume_attachment:
    compartment_id: "{{ compartment_id }}"
    type: iscsi
    instance_id: "{{ r_oci_compute_instance_facts.instances[0].id }}"
    volume_id: "{{ item.volume.id }}"
  with_items: "{{ r_oci_blockstorage_volume_present.results }}"
  register: r_oci_blockstorage_volume_attachment

- debug: var=r_oci_blockstorage_volume_attachment
  delegate_to: localhost
  when: debug | bool
